apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=tags/1.28.0

patchesStrategicMerge:
  - flux-gitrepository.yaml