# This kustomization file can be generated "on-the-fly" by the "transformation flow"
# There is no need to keep it in the repo
# The folder structure could be standartized in this case like
#   hello-world/
#      configs/
#        configmap.yaml
#      overlays
#        flux-gitrepository.yaml
# whatever is "configs" goes under "resources" and all from "overlays" goes under "patchesStrategicMerge"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - git::https://github.com/kaizentm/platform-src.git/apps/hello-world?ref=main         

resources:
  - configmap.yaml

patchesStrategicMerge:
  - flux-gitrepository.yaml
  
